### ISSUE TITLE
Hibernate Exception while sending mail from an asynchronous Event Listener in Grails 2.5.2

### ISSUE THREAD

**Issue by abhaygoel** [kefirfromperm/grails-asynchronous-mail#59] opened 2016-05-20 08:01 UTC
Hi,
Thank you for such a wonderful plugin. I have been using this plugin for quite some time now and absolutely love it.

Recently, I had a use case to send a notification email in an event listener. 
I'm using grails 2.5.2, grails-async - 1.2, hibernate 3.x
Here's my event listener:

`class ExportListenerService implements ApplicationListener<ExportNotificationEvent> {
    def bqExportService
    def asynchronousMailService

/**
 * Handle an application event.
 * @param event the event to respond to
 */

    @Override
    void onApplicationEvent(ExportNotificationEvent event) {
        // get data from event

        def inParam = event.getSource() as Map

        def obj = bqExportService.generateReportAsByteArray(inParam)
        if (!obj?.generatedBytes) {

            log.error("Error Generating report ${obj.reportFileName} - No generated bytes")
           
        } else if (obj.generatedBytes && inParam.nextAction == 'email') {

            asynchronousMailService.sendMail {
                multipart true
                to inParam?.user
                subject "Report ${obj?.reportFileName}.pdf"
                body "Your report is generated and attached with this mail."
                attachBytes "${obj?.reportFileName}.pdf", "application/pdf", obj?.generatedBytes
            }
        }

    }
}
`

I get the following stack trace:
`obj=[reportFileName:Execution_Export-Test_2016-02-11_06:38:03, generatedBytes:[37, 80, 10]]
| Error Exception in thread "pool-1-thread-11" 
| Error org.hibernate.HibernateException: No Hibernate Session bound to thread, and configuration does not allow creation of non-transactional one here
| Error 	at org.springframework.orm.hibernate3.SpringSessionContext.currentSession(SpringSessionContext.java:65)
| Error 	at grails.plugin.hibernatehijacker.hibernate.SessionFactoryInvocationHandler.invoke(SessionFactoryInvocationHandler.java:33)
| Error 	at com.sun.proxy.$Proxy40.getCurrentSession(Unknown Source)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.validation.HibernateDomainClassValidator.validate(HibernateDomainClassValidator.java:58)
| Error 	at org.codehaus.groovy.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:118)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.ValidatePersistentMethod.doInvokeInternal(ValidatePersistentMethod.java:119)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:63)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.AbstractHibernateGormValidationApi.validate(AbstractHibernateGormValidationApi.groovy:57)
| Error 	at grails.plugin.asyncmail.AsynchronousMailMessage.validate(AsynchronousMailMessage.groovy)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:497)
| Error 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432)
| Error 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener$8.call(ClosureEventListener.java:370)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener$8.call(ClosureEventListener.java:352)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener.doWithManualSession(ClosureEventListener.java:345)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener.onPreInsert(ClosureEventListener.java:352)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.EventTriggeringInterceptor.onPreInsert(EventTriggeringInterceptor.java:157)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.EventTriggeringInterceptor.onPersistenceEvent(EventTriggeringInterceptor.java:83)
| Error 	at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:47)
| Error 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
| Error 	at org.springframework.context.event.SimpleApplicationEventMulticaster$1.run(SimpleApplicationEventMulticaster.java:123)
| Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
| Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
| Error 	at java.lang.Thread.run(Thread.java:745)
| Error Exception in thread "pool-1-thread-12" 
| Error org.hibernate.HibernateException: No Hibernate Session bound to thread, and configuration does not allow creation of non-transactional one here
| Error 	at org.springframework.orm.hibernate3.SpringSessionContext.currentSession(SpringSessionContext.java:65)
| Error 	at grails.plugin.hibernatehijacker.hibernate.SessionFactoryInvocationHandler.invoke(SessionFactoryInvocationHandler.java:33)
| Error 	at com.sun.proxy.$Proxy40.getCurrentSession(Unknown Source)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.validation.HibernateDomainClassValidator.validate(HibernateDomainClassValidator.java:58)
| Error 	at org.codehaus.groovy.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:118)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.ValidatePersistentMethod.doInvokeInternal(ValidatePersistentMethod.java:119)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:63)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.AbstractHibernateGormValidationApi.validate(AbstractHibernateGormValidationApi.groovy:57)
| Error 	at grails.plugin.asyncmail.AsynchronousMailAttachment.validate(AsynchronousMailAttachment.groovy)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:497)
| Error 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432)
| Error 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener$8.call(ClosureEventListener.java:370)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener$8.call(ClosureEventListener.java:352)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener.doWithManualSession(ClosureEventListener.java:345)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener.onPreInsert(ClosureEventListener.java:352)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.EventTriggeringInterceptor.onPreInsert(EventTriggeringInterceptor.java:157)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.EventTriggeringInterceptor.onPersistenceEvent(EventTriggeringInterceptor.java:83)
| Error 	at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:47)
| Error 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
| Error 	at org.springframework.context.event.SimpleApplicationEventMulticaster$1.run(SimpleApplicationEventMulticaster.java:123)
| Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
| Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
| Error 	at java.lang.Thread.run(Thread.java:745)
2016-05-20 13:10:59,647 +0530 [quartzScheduler_Worker-2] TRACE AsynchronousMailJob:104  - Entering execute method.
2016-05-20 13:10:59,655 +0530 [ForkJoinPool-10-worker-1] DEBUG AsynchronousMailProcessService:128  - Open a new persistence session.
2016-05-20 13:10:59,664 +0530 [ForkJoinPool-10-worker-1] TRACE AsynchronousMailProcessService:104  - Found a message: grails.plugin.asyncmail.AsynchronousMailMessage(id:105, to:[abhay.goel@bqurious.com], subject:Report Execution_Export-Test_2016-02-11_06:38:03.pdf, status:CREATED)
| Error Exception in thread "pool-1-thread-13" 
| Error org.hibernate.HibernateException: No Hibernate Session bound to thread, and configuration does not allow creation of non-transactional one here
| Error 	at org.springframework.orm.hibernate3.SpringSessionContext.currentSession(SpringSessionContext.java:65)
| Error 	at grails.plugin.hibernatehijacker.hibernate.SessionFactoryInvocationHandler.invoke(SessionFactoryInvocationHandler.java:33)
| Error 	at com.sun.proxy.$Proxy40.getCurrentSession(Unknown Source)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.validation.HibernateDomainClassValidator.validate(HibernateDomainClassValidator.java:58)
| Error 	at org.codehaus.groovy.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:118)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.ValidatePersistentMethod.doInvokeInternal(ValidatePersistentMethod.java:119)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:63)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.AbstractHibernateGormValidationApi.validate(AbstractHibernateGormValidationApi.groovy:57)
| Error 	at grails.plugin.asyncmail.AsynchronousMailMessage.validate(AsynchronousMailMessage.groovy)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:497)
| Error 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432)
| Error 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener$7.call(ClosureEventListener.java:326)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener$7.call(ClosureEventListener.java:316)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener.doWithManualSession(ClosureEventListener.java:345)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener.onPreUpdate(ClosureEventListener.java:316)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.EventTriggeringInterceptor.onPreUpdate(EventTriggeringInterceptor.java:166)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.EventTriggeringInterceptor.onPersistenceEvent(EventTriggeringInterceptor.java:91)
| Error 	at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:47)
| Error 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
| Error 	at org.springframework.context.event.SimpleApplicationEventMulticaster$1.run(SimpleApplicationEventMulticaster.java:123)
| Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
| Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
| Error 	at java.lang.Thread.run(Thread.java:745)
2016-05-20 13:10:59,689 +0530 [ForkJoinPool-10-worker-1] TRACE AsynchronousMailProcessService:104  - Attempt to send the message with id=105.
2016-05-20 13:11:03,414 +0530 [ForkJoinPool-10-worker-1] TRACE AsynchronousMailProcessService:104  - The message with id=105 was sent successfully.
| Error Exception in thread "pool-1-thread-14" 
| Error org.hibernate.HibernateException: No Hibernate Session bound to thread, and configuration does not allow creation of non-transactional one here
| Error 	at org.springframework.orm.hibernate3.SpringSessionContext.currentSession(SpringSessionContext.java:65)
| Error 	at grails.plugin.hibernatehijacker.hibernate.SessionFactoryInvocationHandler.invoke(SessionFactoryInvocationHandler.java:33)
| Error 	at com.sun.proxy.$Proxy40.getCurrentSession(Unknown Source)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.validation.HibernateDomainClassValidator.validate(HibernateDomainClassValidator.java:58)
| Error 	at org.codehaus.groovy.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:118)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.ValidatePersistentMethod.doInvokeInternal(ValidatePersistentMethod.java:119)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:63)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.AbstractHibernateGormValidationApi.validate(AbstractHibernateGormValidationApi.groovy:57)
| Error 	at grails.plugin.asyncmail.AsynchronousMailMessage.validate(AsynchronousMailMessage.groovy)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:497)
| Error 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432)
| Error 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener$7.call(ClosureEventListener.java:326)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener$7.call(ClosureEventListener.java:316)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener.doWithManualSession(ClosureEventListener.java:345)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventListener.onPreUpdate(ClosureEventListener.java:316)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.EventTriggeringInterceptor.onPreUpdate(EventTriggeringInterceptor.java:166)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.EventTriggeringInterceptor.onPersistenceEvent(EventTriggeringInterceptor.java:91)
| Error 	at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:47)
| Error 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
| Error 	at org.springframework.context.event.SimpleApplicationEventMulticaster$1.run(SimpleApplicationEventMulticaster.java:123)
| Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
| Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
| Error 	at java.lang.Thread.run(Thread.java:745)
2016-05-20 13:11:03,454 +0530 [ForkJoinPool-10-worker-1] TRACE AsynchronousMailProcessService:104  - The message with id=105 was deleted.
2016-05-20 13:11:03,455 +0530 [ForkJoinPool-10-worker-1] DEBUG AsynchronousMailProcessService:128  - Flush the persistence session.
2016-05-20 13:11:03,455 +0530 [ForkJoinPool-10-worker-1] DEBUG AsynchronousMailProcessService:128  - Destroy the persistence session.
2016-05-20 13:11:03,456 +0530 [quartzScheduler_Worker-2] TRACE AsynchronousMailJob:104  - Exiting execute method. Execution time = 3808ms
2016-05-20 13:11:59,646 +0530 [quartzScheduler_Worker-1] TRACE AsynchronousMailJob:104  - Entering execute method.
2016-05-20 13:11:59,657 +0530 [quartzScheduler_Worker-1] TRACE AsynchronousMailJob:104  - Exiting execute method. Execution time = 10ms
2016-05-20 13:12:59,649 +0530 [quartzScheduler_Worker-3] TRACE AsynchronousMailJob:104  - Entering execute method.
2016-05-20 13:12:59,655 +0530 [quartzScheduler_Worker-3] TRACE AsynchronousMailJob:104  - Exiting execute method. Execution time = 6ms
2016-05-20 13:13:06,750 +0530 [quartzScheduler_Worker-4] TRACE ExpiredMessagesCollectorJob:104  - Entering execute method.
2016-05-20 13:13:06,755 +0530 [quartzScheduler_Worker-4] TRACE AsynchronousMailPersistenceService:104  - 0 expired messages were updated.
2016-05-20 13:13:06,757 +0530 [quartzScheduler_Worker-4] TRACE ExpiredMessagesCollectorJob:104  - Exiting execute method.
201`

Please advice.

**Comment by kefirfromperm** [comment] 2016-05-20 12:40
Hello,

You are trying to use the plugin in environment where a hibernate session is absent. Just use `withNew Session`. http://docs.grails.org/2.5.x/ref/Domain%20Classes/withNewSession.html

```groovy
AsynchronousMailMessage.withNewSession {
    asynchronousMailService.sendMail {
          multipart true
          to inParam?.user
          subject "Report ${obj?.reportFileName}.pdf"
          body "Your report is generated and attached with this mail."
          attachBytes "${obj?.reportFileName}.pdf", "application/pdf", obj?.generatedBytes
    }
}
```

If it will be OK, please close this issue.

**Comment by abhaygoel** [comment] 2016-05-20 12:48
Thanks a lot Vitali. Appreciate your help. 

 

I’ll close the issue.

 

Regards,

Abhay

**Comment by abhaygoel** [comment] 2016-05-20 13:29
Hi Vitalii,

Unfortunately, I’m getting another error this time. 

 

Here’s the updated code:

AsynchronousMailMessage.withNewSession {
    asynchronousMailService.sendMail {
        multipart true
        to user
        subject "Report ${reportFileName}.pdf"
        body "Your report is generated and attached with this mail."

        attach("${reportFileName}.pdf", "application/pdf", generatedBytes)
    }
}

 

Stacktrace:

 

 

grails.validation.ValidationException: Validation Error(s) occurred during save():

- Field error in object 'grails.plugin.asyncmail.AsynchronousMailMessage' on field 'attachments[0].attachmentName': rejected value [null]; codes [grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.error.grails.plugin.asyncmail.AsynchronousMailMessage.attachments[0].attachmentName,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.error.grails.plugin.asyncmail.AsynchronousMailMessage.attachments.attachmentName,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.error.attachments[0].attachmentName,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.error.attachments.attachmentName,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.error.attachmentName,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.error.java.lang.String,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.error,asynchronousMailAttachment.attachmentName.nullable.error.grails.plugin.asyncmail.AsynchronousMailMessage.attachments[0].attachmentName,asynchronousMailAttachment.attachmentName.nullable.error.grails.plugin.asyncmail.AsynchronousMailMessage.attachments.attachmentName,asynchronousMailAttachment.attachmentName.nullable.error.attachments[0].attachmentName,asynchronousMailAttachment.attachmentName.nullable.error.attachments.attachmentName,asynchronousMailAttachment.attachmentName.nullable.error.attachmentName,asynchronousMailAttachment.attachmentName.nullable.error.java.lang.String,asynchronousMailAttachment.attachmentName.nullable.error,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments[0].attachmentName,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments.attachmentName,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.attachments[0].attachmentName,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.attachments.attachmentName,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.attachmentName,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable.java.lang.String,grails.plugin.asyncmail.AsynchronousMailAttachment.attachmentName.nullable,asynchronousMailAttachment.attachmentName.nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments[0].attachmentName,asynchronousMailAttachment.attachmentName.nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments.attachmentName,asynchronousMailAttachment.attachmentName.nullable.attachments[0].attachmentName,asynchronousMailAttachment.attachmentName.nullable.attachments.attachmentName,asynchronousMailAttachment.attachmentName.nullable.attachmentName,asynchronousMailAttachment.attachmentName.nullable.java.lang.String,asynchronousMailAttachment.attachmentName.nullable,nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments[0].attachmentName,nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments.attachmentName,nullable.attachments[0].attachmentName,nullable.attachments.attachmentName,nullable.attachmentName,nullable.java.lang.String,nullable]; arguments [attachmentName,class grails.plugin.asyncmail.AsynchronousMailAttachment]; default message [Property [{0}] cannot be null]

- Field error in object 'grails.plugin.asyncmail.AsynchronousMailMessage' on field 'attachments[0].content': rejected value [null]; codes [grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.error.grails.plugin.asyncmail.AsynchronousMailMessage.attachments[0].content,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.error.grails.plugin.asyncmail.AsynchronousMailMessage.attachments.content,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.error.attachments[0].content,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.error.attachments.content,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.error.content,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.error.[B,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.error,asynchronousMailAttachment.content.nullable.error.grails.plugin.asyncmail.AsynchronousMailMessage.attachments[0].content,asynchronousMailAttachment.content.nullable.error.grails.plugin.asyncmail.AsynchronousMailMessage.attachments.content,asynchronousMailAttachment.content.nullable.error.attachments[0].content,asynchronousMailAttachment.content.nullable.error.attachments.content,asynchronousMailAttachment.content.nullable.error.content,asynchronousMailAttachment.content.nullable.error.[B,asynchronousMailAttachment.content.nullable.error,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments[0].content,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments.content,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.attachments[0].content,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.attachments.content,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.content,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable.[B,grails.plugin.asyncmail.AsynchronousMailAttachment.content.nullable,asynchronousMailAttachment.content.nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments[0].content,asynchronousMailAttachment.content.nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments.content,asynchronousMailAttachment.content.nullable.attachments[0].content,asynchronousMailAttachment.content.nullable.attachments.content,asynchronousMailAttachment.content.nullable.content,asynchronousMailAttachment.content.nullable.[B,asynchronousMailAttachment.content.nullable,nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments[0].content,nullable.grails.plugin.asyncmail.AsynchronousMailMessage.attachments.content,nullable.attachments[0].content,nullable.attachments.content,nullable.content,nullable.[B,nullable]; arguments [content,class grails.plugin.asyncmail.AsynchronousMailAttachment]; default message [Property [{0}] cannot be null]

                at grails.plugin.asyncmail.AsynchronousMailPersistenceService.save(AsynchronousMailPersistenceService.groovy:8)

                at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)

                at grails.plugin.asyncmail.AsynchronousMailService$_sendAsynchronousMail_closure1.doCall(AsynchronousMailService.groovy:42)

                at grails.plugin.asyncmail.AsynchronousMailService.sendAsynchronousMail(AsynchronousMailService.groovy:41)

                at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)

                at AsynchronousMailGrailsPlugin$_configureSendMail_closure8.doCall(AsynchronousMailGrailsPlugin.groovy:128)

                at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)

                at MailGrailsPlugin$_configureSendMail_closure7.doCall(MailGrailsPlugin.groovy:175)

                at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)

                at com.bq.export.BqExportService$__tt__generateReportAsByteArray_closure7.doCall(BqExportService.groovy:252)

                at com.bq.export.BqExportService.$tt__generateReportAsByteArray(BqExportService.groovy:251)

                at GrailsMelodyGrailsPlugin$_closure4$_closure16$_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)

                at com.bq.export.BqExportController$_generateReportAndMail_closure1.doCall(BqExportController.groovy:41)

                at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)

                at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)

                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

                at java.lang.Thread.run(Thread.java:745)

2016-05-20 18:56:21,706 +0530 [Actor Thread 1] TRACE AsynchronousMailService:104  - Start send job immediately.

2016-05-20 18:56:21,718 +0530 [quartzScheduler_Worker-4] TRACE AsynchronousMailJob:104  - Entering execute method.

2016-05-20 18:56:21,728 +0530 [quartzScheduler_Worker-4] TRACE AsynchronousMailJob:104  - Exiting execute method. Execution time = 10ms

**Comment by kefirfromperm** [comment] 2016-05-20 17:22
Try to set
grailsApplication.config.asynchronous.mail.newSessionOnImmediateSend = false

**Comment by abhaygoel** [comment] 2016-05-21 04:48
Hi Vitalli,

No luck Still the same problem. 

 

Regards,

Abhay

**Comment by kefirfromperm** [comment] 2016-05-21 07:06
Please print all parameters `"${reportFileName}.pdf", "application/pdf", generatedBytes` before call attach. All of them is not null and not blank?

**Comment by abhaygoel** [comment] 2016-05-21 07:10
Yup. Already did that. I have printed them inside the sendMail closure and all are not null. I have tried with standard mail plugin (non-asynchronous) and it works fine.

**Comment by kefirfromperm** [comment] 2016-05-22 05:18
Which database do you use?
Please attach latest log.

**Comment by puneetbehl** [comment] 2016-05-22 18:03
@abhaygoel Maybe you could create a sample application describing the problem scenario and share the github link here so that we can try to solve it.

**Comment by kefirfromperm** [comment] 2016-08-02 15:59
Can't reproduce.

**Closed by kefirfromperm** 2016-08-02 15:59 UTC
Labels: bug
